version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: my-psql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sso
    ports:
      - "5500:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "sso"]
      interval: 10s
      timeout: 10s
      retries: 5
  
  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6600:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: ["redis-server", "--requirepass", admin]
  
  migrator:
    build: 
      context: .
      dockerfile: Dockerfile.migrator
    container_name: my-migrator
    depends_on:
      - db
    
  app:
    build: 
     context: .
     dockerfile: Dockerfile.app
    container_name: my-app
    ports:
      - "44044:44044"
    depends_on:
      - redis
      - db
      - migrator