FROM golang:latest

RUN mkdir /app
WORKDIR /app
ENV CONFIG_PATH=./config/remote.yaml
ENV POSTGRES_PASS=admin

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/migrator/main.go ./cmd/migrator/main.go
COPY ./config/remote.yaml ./config/remote.yaml
COPY ./migrations ./migrations
COPY ./internal/config ./internal/config
COPY ./internal/logger ./internal/logger
COPY ./internal/lib ./internal/lib

RUN go build -o cmd/migrator ./cmd/migrator/main.go

CMD ["/app/cmd/migrator/main"]