CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    "login" TEXT NOT NULL UNIQUE,
    pass_hash BYTEA NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS login_index ON users("login");

CREATE TABLE IF NOT EXISTS apps
(
    id SERIAL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "secret" TEXT NOT NULL
)