env: # local/dev/prod
migrations_path: #enter your path
tokenTTL: # 1h

storage:
  type: # "mysql", "mongodb", "postgres" or another db
  host: # "localhost" or another host
  port: # 5432 or your free port
  username: # "postgres"
  dbname: # "sso"

cache:
  driver: # "redis"
  host: # "localhost"
  port: # 6379 or your free port
  db: # 0-15 default or your setting

grpc:
  port: # 44044 or your free port
  timeout: # 5s